# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ZENv
email: opensource@zoosk.com
description: > # this means to ignore newlines until "baseurl:"
  Bringing ZEN to your dev environment
baseurl: "/zenv" # the subpath of your site, e.g. /blog
url: "http://zoosk.github.io" # the base hostname & protocol for your site
github_location: "https://github.com/zoosk/zenv"
twitter_username:
github_username:

# Build settings
markdown: kramdown
